### PR TITLE
Remove id, and replace it by name to avoid confusion with index

### PR DESCRIPTION
**Pull request by haudren**
This is the re-opening of https://github.com/jorisv/RBDyn/pull/12

Maybe one should wait until Tasks and other packages are adapted to this change to merge into master.

### CODE REVIEW

**Comment by gergondet** [comment]
This looks nice. Can you squash it into a single commit?

**Comment by haudren** [comment]
No problem ! I'll make it a giant commit :cake:

**Comment by haudren** [comment]
The build failed because the IK module that was just merged was still using the numerical ID. Fixed it, and let's see if the build succeeds :)

**Comment by haudren** [comment]
Build passed on Travis & AppVeyor, I think this is mergeable :fireworks:

**Comment by gergondet** [comment]
:+1:

**Pull request merged**
